name: Gulpease Index Manual
on:
  workflow_dispatch: # per esecuzione manuale
    inputs:
     folder:
        description: "path della cartella da analizzare"
        required: false
        default: ""
jobs:
  test-gulpease:
    runs-on: ubuntu-latest
    outputs:
      idx: ${{ steps.value.outputs.idx }}
    steps:
      - uses: actions/checkout@v3
      - name: Validate the folder path
        id: validate
        run: | 
          folder="${{ github.event.inputs.folder }}"
          if [ ! -d "$folder" ]; then
            echo "The folder doesn't esist : $folder"
            exit 1
          fi
          echo "Folder check : $folder"
      - name : Calulate Gulpease index
        id: value
        run: |
          folder="${{ github.event.inputs.folder }}"
          echo "processing of .tex file in the folder : $folder"
          
          # call the python script
          value=$(python3 .github/gulpease.py "$folder")
          echo "idx=$value" >> "$GITHUB_OUTPUT"
  comment:
    runs-on: ubuntu-latest
    needs: test-gulpease
    steps:
      - name: mostrare indice nel log
        run: |
          echo "Indice di Gulpease medio per questo documento è: ${{ needs.test-gulpease.outputs.idx }}"
